### ISSUE TITLE
gh-pages, remote theme, build error

### ISSUE THREAD

**Issue by TangoYankee** [18F/federalist-uswds-template#21]
**Template:** 
uswds-jekyll

**Files Affected**
footer.yml, config.yml

**Description**
Error & Fix Report:
- I attempted to serve the uswds-jekyll remote theme on GitHub-Pages with a fork of 18F/federalist-uswds-template. 
- Github threw an error, stating that the uswds-jekyll theme is not supported. 
- The error was stopped by going into config.yml and commenting out :
```
 github:
   organization: TravisSpark
   repository: spark-website
   default_branch: gh-pages
```

**Site repo:** 
- Repo: travisspark/spark-website
- Live Site: https://travisspark.github.io/spark-website/
